version: "3.8"

networks:
    appnet:
        driver: "bridge" 

services:
  bapdb:
    image: mysql:5
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: esteem
      MYSQL_DATABASE: bap
    networks: 
      - appnet
    ports:
      - 3306:3306

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - bapdb
    volumes:
      - /usr/app/
    networks: 
      - appnet
    ports:
      - 3007:3007

    # environment:
    #   DB_CONNECTION: pg
    #   DB_HOST: db ## same as the database service name
    #   DB_PORT: 5432
    #   DB_USER: postgres
    #   DB_DATABASE: notesdb
    #   DB_PASSWORD: 63eaQB9wtLqmNBpg
